drop table if exists bookmarks;

create table bookmarks (
  id INTEGER primary key generated by default as identity,
  name text NOT NULL,
  url text NOT NULL,
  rating INTEGER,
  description text
);

insert into bookmarks (name, url, rating, description)
values
  ('Google', 'http://www.google.com', 5, 'Lorem ipsum donor set'),
  ('Test', 'http://www.test.com', 5, 'Lorem ipsum donor set'),
  ('Jest', 'http://www.jest.com', 5, 'Lorem ipsum donor set'),
  ('Best', 'http://www.best.com', 5, 'Lorem ipsum donor set'),
  ('Cest', 'http://www.cest.com', 5, 'Lorem ipsum donor set'),
  ('Rest', 'http://www.rest.com', 5, 'Lorem ipsum donor set'),
  ('Dest', 'http://www.dest.com', 5, 'Lorem ipsum donor set'),
  ('Zest', 'http://www.zest.com', 5, 'Lorem ipsum donor set'),
  ('Yest', 'http://www.yest.com', 5, 'Lorem ipsum donor set'),
  ('Breast', 'http://www.breast.com', 5, 'Lorem ipsum donor set'),
  ('Mest', 'http://www.mest.com', 5, 'Lorem ipsum donor set'),
  ('Nest', 'http://www.nest.com', 5, 'Lorem ipsum donor set'),
  ('Lest', 'http://www.lest.com', 5, 'Lorem ipsum donor set');
